# Generated by Django 2.2 on 2019-06-07 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='Anonimo', max_length=255, verbose_name='Nombre autor')),
                ('last_name', models.CharField(default='Anonimo apellido', max_length=255, verbose_name='Apellido autor')),
                ('age', models.IntegerField(default=0, verbose_name='Edad del Author')),
                ('gender', models.CharField(choices=[('MASCULINO', 'Masculino'), ('FEMENINO', 'Femenino')], max_length=3, verbose_name='genero del Autor')),
                ('biography', models.TextField(verbose_name='Biografia del autor')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/author')),
            ],
        ),
    ]
